import Foundation
import MyTermCore
import MyTermRemoteProtocol
import XCTest

@testable import MyTermRemoteHost

/// A seeded mutation fuzzer over everything that reads text out of a transcript.
///
/// Real transcript lines are flipped, cut, doubled and spliced at random, then fed through the
/// reader, the markdown splitter, the title sanitiser and the marker parser. The only assertions
/// are the ones that hold for any input: nothing crashes, no single input takes longer than a
/// person would wait, and nothing the reader produces is larger than the frame a device accepts.
///
/// `MYTERM_FUZZ_SECONDS` sets the budget (default 3, so the suite stays quick; the round-two QA
/// pass ran it at 60). `MYTERM_FUZZ_SEED` replays one run. Every failure message carries the seed
/// and the iteration, and the failing input is written beside the temporary directory.
final class AgentTranscriptFuzzTests: XCTestCase {
    private let reader = AgentTranscriptReader()

    /// Lines of the shapes a live Claude Code session writes, with the odd corners already in:
    /// escapes, combining marks, a surrogate pair, markdown of every block kind.
    private static let corpus: [String] = [
        #"{"type":"user","uuid":"u1","timestamp":"2026-09-07T04:42:39.983Z","message":{"role":"user","content":"fix the build"}}"#,
        ##"{"type":"assistant","uuid":"a1","timestamp":"2026-09-07T04:42:41.100Z","message":{"role":"assistant","model":"claude-opus-5","content":[{"type":"thinking","thinking":"weighing it up","signature":"x"},{"type":"text","text":"# Plan\n\n- [ ] one\n- [x] two\n\n| a | b |\n|:--|--:|\n| 1 | 2 |\n\n```swift\nlet x = 1\n```\n\n> quoted\n\n---\n\n1. first\n2. second"}]}}"##,
        #"{"type":"assistant","uuid":"a2","message":{"role":"assistant","model":"claude-opus-5","content":[{"type":"tool_use","id":"toolu_01","name":"Bash","input":{"command":"rm -rf build","description":"Clean the build"}}]}}"#,
        #"{"type":"user","uuid":"u2","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"toolu_01","content":"removed 'build'\n\u001b[31mred\u001b[0m"}]}}"#,
        #"{"type":"user","uuid":"u3","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"toolu_02","is_error":true,"content":[{"type":"text","text":"no such file"},{"type":"image","source":{"type":"base64","data":"AAAA"}}]}]}}"#,
        #"{"type":"assistant","uuid":"a3","message":{"role":"assistant","content":[{"type":"tool_use","id":"toolu_03","name":"Agent","input":{"subagent_type":"Explore","description":"Find the reader","prompt":"Look for where transcripts are read"}}]}}"#,
        #"{"type":"assistant","uuid":"a4","message":{"role":"assistant","content":[{"type":"tool_use","id":"toolu_04","name":"SendMessage","input":{"to":"docs-mac","message":"done"}}]}}"#,
        #"{"type":"user","uuid":"u4","message":{"role":"user","content":"<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus</command-args>"}}"#,
        #"{"type":"user","uuid":"u5","message":{"role":"user","content":"<local-command-stdout>Set model to \u001b[1mOpus 5\u001b[22m</local-command-stdout>"}}"#,
        #"{"type":"user","uuid":"u6","isMeta":true,"message":{"role":"user","content":"Caveat: the messages below were generated by the user while running local commands."}}"#,
        #"{"type":"user","uuid":"u7","isCompactSummary":true,"message":{"role":"user","content":"This session is being continued from a previous conversation"}}"#,
        #"{"type":"system","uuid":"s1","subtype":"compact_boundary","content":"Conversation compacted","compactMetadata":{"trigger":"auto","preTokens":140000}}"#,
        #"{"type":"system","uuid":"s2","subtype":"informational","level":"warning","content":"Connection lost; retrying"}"#,
        #"{"type":"system","uuid":"s3","subtype":"local_command","content":"<command-name>/clear</command-name>"}"#,
        #"{"type":"ai-title","aiTitle":"✳ Rename the tabs","sessionId":"87d84ef0-4227-42d8-92e3-3dafcf13979f"}"#,
        #"{"type":"file-history-snapshot","messageId":"m1","snapshot":{"trackedFileBackups":{}}}"#,
        #"{"type":"user","uuid":"u8","message":{"role":"user","content":"café 🙂 é ‮evil ​‍"}}"#,
        #"{"type":"assistant","uuid":"a5","message":{"role":"assistant","content":[{"type":"text","text":"Nested **bold *and italic* text** with `code` and [a link](https://example.com) and | pipes | in | prose"}]}}"#,
    ]

    /// Bytes worth inserting because parsers care about them: JSON structure, escape starts,
    /// markdown markers, terminal controls, invalid and combining UTF-8.
    private static let interesting: [[UInt8]] = [
        Array("\"".utf8), Array("\\".utf8), Array("{".utf8), Array("}".utf8), Array("[".utf8), Array("]".utf8),
        Array(",".utf8), Array(":".utf8), Array("\\u".utf8), Array("\\ud800".utf8), Array("\\udc00".utf8),
        Array("\\n".utf8), Array("\n".utf8), Array("\r\n".utf8), Array("|".utf8), Array("---".utf8),
        Array("```".utf8), Array("# ".utf8), Array("- [ ] ".utf8), Array("> ".utf8), Array("1. ".utf8),
        [0x1B, 0x5B], [0x1B, 0x5D], [0x07], [0x00], [0x7F], [0x9B], [0xFF], [0xC0, 0x80], [0xED, 0xA0, 0x80],
        [0xCC, 0x81], Array("\u{FEFF}".utf8), Array("\u{202E}".utf8), Array("<command-name>".utf8),
        Array("<local-command-stdout>".utf8), Array("\"type\":\"tool_use\"".utf8), Array("\"type\":\"ai-title\"".utf8),
        Array("\"uuid\":\"".utf8), Array("agent=claude;event=finished;session=".utf8),
    ]

    func testMutatedTranscriptsNeverCrashHangOrOverflowAFrame() throws {
        let environment = ProcessInfo.processInfo.environment
        let seconds = TimeInterval(environment["MYTERM_FUZZ_SECONDS"] ?? "") ?? 3
        let seed = UInt64(environment["MYTERM_FUZZ_SEED"] ?? "") ?? UInt64.random(in: 0...UInt64.max)
        var random = SplitMix64(seed: seed)
        let corpusBytes = Self.corpus.map { Array($0.utf8) }

        let deadline = Date().addingTimeInterval(seconds)
        var iterations = 0
        var largestFrame = 0
        var slowest: TimeInterval = 0

        while Date() < deadline {
            iterations += 1
            let context = "seed \(seed), iteration \(iterations)"

            // Between one and eight lines, each a mutated copy of a corpus line, some spliced.
            var lines: [String] = []
            for _ in 0..<Int(random.next(in: 1...8)) {
                var bytes = corpusBytes[Int(random.next(in: 0...UInt64(corpusBytes.count - 1)))]
                for _ in 0..<Int(random.next(in: 0...6)) {
                    Self.mutate(&bytes, random: &random, corpus: corpusBytes)
                }
                lines.append(String(decoding: bytes, as: UTF8.self))
            }

            let start = Date()
            let conversation = reader.conversation(tabID: "tab", agent: "claude", lines: lines)
            let entries = reader.entries(from: lines)
            for line in lines {
                _ = reader.entry(from: line)
                _ = reader.title(from: line)
                _ = AgentSessionTitle.sanitized(line)
                _ = AgentActivityMarker.report(fromPayload: line)
                _ = AgentTranscriptReader.presentable(line)
                _ = AgentMarkdown.blocks(in: line)
            }
            for entry in conversation.entries + entries {
                for block in entry.blocks {
                    switch block {
                    case .text(let text), .thinking(let text):
                        _ = AgentMarkdown.blocks(in: text)
                    case .toolResult(let result):
                        _ = AgentMarkdown.blocks(in: result.text)
                    case .localCommand(let command):
                        _ = AgentMarkdown.blocks(in: command.output)
                    case .toolUse(let use):
                        _ = AgentMarkdown.blocks(in: use.detail)
                    case .note(let note):
                        _ = AgentMarkdown.blocks(in: note.text)
                    case .image:
                        break
                    }
                }
            }
            let frame = try RemoteControlCodec.encode(.agentConversation(conversation))
            let updates = try RemoteControlCodec.encode(.agentEntries(RemoteAgentEntries(tabID: "tab", entries: entries)))
            let elapsed = Date().timeIntervalSince(start)

            largestFrame = max(largestFrame, frame.payload.count, updates.payload.count)
            slowest = max(slowest, elapsed)
            if frame.payload.count > RemoteFrameCodec.maximumFrameBytes
                || updates.payload.count > RemoteFrameCodec.maximumFrameBytes
                || elapsed > 5 {
                let dump = Self.dump(lines, context: context)
                XCTFail("\(context): frame \(frame.payload.count) / \(updates.payload.count) bytes, \(elapsed)s; input at \(dump.path)")
                return
            }
        }
        print("fuzz: \(iterations) iterations in \(seconds)s, seed \(seed), largest frame \(largestFrame) bytes, slowest \(slowest)s")
    }

    // MARK: - Mutation

    private static func mutate(_ bytes: inout [UInt8], random: inout SplitMix64, corpus: [[UInt8]]) {
        switch random.next(in: 0...6) {
        case 0 where !bytes.isEmpty:
            // Flip bits in one byte.
            let index = Int(random.next(in: 0...UInt64(bytes.count - 1)))
            bytes[index] ^= UInt8(truncatingIfNeeded: random.next(in: 1...255))
        case 1 where !bytes.isEmpty:
            // Truncate.
            let keep = Int(random.next(in: 0...UInt64(bytes.count)))
            bytes = Array(bytes.prefix(keep))
        case 2 where bytes.count > 1:
            // Duplicate a range, sometimes many times over.
            let from = Int(random.next(in: 0...UInt64(bytes.count - 1)))
            let to = min(bytes.count, from + Int(random.next(in: 1...64)))
            let times = Int(random.next(in: 1...(random.next(in: 0...9) == 0 ? 2_000 : 4)))
            let slice = Array(bytes[from..<to])
            var copies: [UInt8] = []
            for _ in 0..<times { copies.append(contentsOf: slice) }
            bytes.insert(contentsOf: copies, at: to)
        case 3:
            // Insert something a parser cares about.
            let piece = interesting[Int(random.next(in: 0...UInt64(interesting.count - 1)))]
            let at = bytes.isEmpty ? 0 : Int(random.next(in: 0...UInt64(bytes.count)))
            bytes.insert(contentsOf: piece, at: at)
        case 4:
            // Insert random bytes.
            let count = Int(random.next(in: 1...16))
            let at = bytes.isEmpty ? 0 : Int(random.next(in: 0...UInt64(bytes.count)))
            bytes.insert(contentsOf: (0..<count).map { _ in UInt8(truncatingIfNeeded: random.next(in: 0...255)) }, at: at)
        case 5:
            // Splice in the tail of another corpus line.
            let other = corpus[Int(random.next(in: 0...UInt64(corpus.count - 1)))]
            let from = Int(random.next(in: 0...UInt64(other.count - 1)))
            let at = bytes.isEmpty ? 0 : Int(random.next(in: 0...UInt64(bytes.count)))
            bytes.insert(contentsOf: other[from...], at: at)
        case 6 where bytes.count > 1:
            // Delete a range.
            let from = Int(random.next(in: 0...UInt64(bytes.count - 1)))
            let to = min(bytes.count, from + Int(random.next(in: 1...32)))
            bytes.removeSubrange(from..<to)
        default:
            break
        }
    }

    private static func dump(_ lines: [String], context: String) -> URL {
        let url = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("myterm-fuzz-\(context.replacingOccurrences(of: " ", with: "-").replacingOccurrences(of: ",", with: "")).jsonl")
        try? lines.joined(separator: "\n").write(to: url, atomically: true, encoding: .utf8)
        return url
    }
}

/// A small deterministic generator, so a failing run can be replayed from its seed.
struct SplitMix64 {
    private var state: UInt64

    init(seed: UInt64) {
        state = seed
    }

    mutating func next() -> UInt64 {
        state &+= 0x9E37_79B9_7F4A_7C15
        var z = state
        z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
        z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
        return z ^ (z >> 31)
    }

    mutating func next(in range: ClosedRange<UInt64>) -> UInt64 {
        let span = range.upperBound - range.lowerBound
        guard span < UInt64.max else { return next() }
        return range.lowerBound + next() % (span + 1)
    }
}
